#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

##########  MY CODE ##########
def diagonalDifference(N):
    
    
    for i in range(len(N)):
        if -100<=N[i][i]<=100:
            Diag_1=0
            for j in range (len(N)):
                Diag_1+=N[j][j]
            Diag_2=0
            for k in range(len(N)):
                Diag_2+=N[k][len(N)-k-1]
            Diff_req=abs(Diag_1 - Diag_2)
    return (Diff_req) 



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
