#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#


####### MY SOLUTION ########
def compareTriplets(alice_array,bob_array):
    
    Final_list=[0,0]
    if 0<=alice_array[0]<=100 and 0<=alice_array[1]<=100 and 0<=alice_array[2]<=100 and 0<=bob_array[0]<=100 and 0<=bob_array[1]<=100 and 0<=bob_array[2]<=100:
         for j in range(3):
                
                    if alice_array[j]>bob_array[j]:
                        Final_list[0]+=1 
                    elif alice_array[j]<bob_array[j]:
                        Final_list[1]+=1
    return(Final_list)




    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
